stages:
  - test
  - build
  - deploy

variables:
  NODE_ENV: production

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm test
  only:
    - master

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
  environment:
    name: production
    url: https://rocketalert.live
  only:
    - master
  variables:
    REACT_APP_MAPBOX_ACCESS_TOKEN_ALERT_LOCATION: $MAPBOX_ACCESS_TOKEN_ALERT_LOCATION
    REACT_APP_MAPBOX_ACCESS_TOKEN_USER_LOCATION: $MAPBOX_ACCESS_TOKEN_USER_LOCATION

deploy:
  stage: deploy
  script:
    - npm run predeploy
    - npm run deploy
  only:
    - master

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r build/* .public
  artifacts:
    paths:
      - .public
  only:
    - master