name: Test and Build

on:
  push:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build 🔧
        run: npm run build
        env:
          REACT_APP_MAPBOX_ACCESS_TOKEN_ALERT_LOCATION: ${{ secrets.MAPBOX_ACCESS_TOKEN_ALERT_LOCATION }}
          REACT_APP_MAPBOX_ACCESS_TOKEN_USER_LOCATION: ${{ secrets.MAPBOX_ACCESS_TOKEN_USER_LOCATION }}

      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: build
